baseURL: https://clairezhang.netlify.app/
languageCode: en-us
title: Cliare's Portfolio
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    #subtitle: |-
    #  A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
    #  AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Hi, my name is Claire Zhang. Welcome to my R portfolio website!
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
        street: Park Road
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: clairezhang22@outlook.com
        title: Email
    enable: yes
    phone:
      - phone: (206) 698-5410
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: ClaireZhang
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
     # - icon: fa-twitter
    #    label: Twitter
     #   url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/profile.php?id=100004821061044
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/clairrre__/
      - icon: fa-github
        label: GitHub
        url: https://github.com/clairezhang22
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/clairezhanghanwen/
  image: ''
  name: Claire Zhang
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      #- name: Generic Blog
      #  url: blogs/ipsum
      #- name: Elements
      #  url: elements.html
    menu: Menu
    #subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpg
        subtitle: About me
        title: Biography
        url: blogs/claire_intro
      - image: yield_curve.jpeg
        subtitle: R project 1
        title: Yield Curve Analysis
        url: blogs/yield_curve
      - image: gdp.jpeg
        subtitle: R project 2
        title: GDP Analysis
        url: blogs/gdp
      - image: air.jpeg
        subtitle: The ultimate group R project
        title: Airbnb Project
        url: blogs/airbnb
      - image: finance.jpg
        subtitle: To learn more about me
        title: Why Finance?
        url: blogs/finance
      - image: mmr.jpeg
        subtitle: SLet's enjoy a slide show!
        title: Memories
        url: blogs/mmr
  two:
    buttonText: Get Started
    enable: yes
    #subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    #title: Massa libero
    url: blogs
